daemon: false

log:
  displayLevel: 2
  fileLevel: 2
  useSyslog: false
  filePath: /home/quantar/quantar-runtime/log
  activityFilePath: /home/quantar/quantar-runtime/log
  fileRoot: dvmbridge-dmr-to-p25

network:
  id: 9000112
  address: 127.0.0.1
  port: 62031
  password: "LOCAL_FNE_PASSWORD"
  encrypted: false
  presharedKey: ""
  allowDiagnosticTransfer: true
  packetDump: false
  debug: false
  sourceId: 9000199
  overrideSourceIdFromMDC: false
  overrideSourceIdFromUDP: true
  resetCallForSourceIdChange: true
  destinationId: 0
  slot: 2

system:
  identity: BRIDGE-PCM-P25-ONLY
  netId: BB800
  sysId: 001
  grantDemand: false
  txMode: 2
  rxAudioGain: 0.3
  vocoderDecoderAudioGain: 0.4
  vocoderDecoderAutoGain: false
  vocoderDecoderUvQuality: 12
  txAudioGain: 1.10
  vocoderEncoderAudioGain: 0.0
  p25EncodePresenceGain: 0.0
  p25EncodeHighCutHz: 2500
  p25EncodeAgc: false
  p25EncodeAgcPeakLimit: 24000
  trace: false
  debug: false
  tek:
    enable: false
    tekAlgo: "aes"
    tekKeyId: 1
  localAudio: false
  voxSampleLevel: 80.0
  dropTimeMs: 500
  detectAnalogMDC1200: false
  preambleLeaderTone: false
  preambleTone: 2175
  preambleLength: 200
  udpAudio: true
  udpMetadata: true
  udpSendPort: 31123
  udpSendAddress: "127.0.0.1"
  udpReceivePort: 31121
  udpReceiveAddress: "127.0.0.1"
  udpRTPFrames: true
  udpIgnoreRTPTiming: true
  udpRTPContinuousSeq: false
  udpUseULaw: false
  udpUsrp: false
  udpFrameTiming: false
  rtsPttEnable: false
  rtsPttPort: "/dev/ttyUSB0"
  rtsPttHoldoffMs: 250
  ctsCorEnable: false
  ctsCorPort: "/dev/ttyUSB0"
  ctsCorInvert: false
  ctsCorHoldoffMs: 250
