daemon: false

log:
  displayLevel: 2
  fileLevel: 2
  useSyslog: false
  filePath: /home/quantar/quantar-runtime/log
  activityFilePath: /home/quantar/quantar-runtime/log
  fileRoot: dvmbridge-p25-to-dmr

network:
  id: 9000111
  address: 127.0.0.1
  port: 62031
  password: "LOCAL_FNE_PASSWORD"
  encrypted: false
  presharedKey: ""
  allowDiagnosticTransfer: true
  packetDump: false
  debug: false
  sourceId: 9000199
  overrideSourceIdFromMDC: false
  overrideSourceIdFromUDP: true
  resetCallForSourceIdChange: true
  destinationId: 0
  slot: 2

system:
  identity: BRIDGE-P25-PCM-ONLY
  netId: BB800
  sysId: 001
  grantDemand: false
  txMode: 1
  rxAudioGain: 1.0
  vocoderDecoderAudioGain: 1.0
  vocoderDecoderAutoGain: false
  vocoderDecoderUvQuality: 12
  txAudioGain: 2.0
  vocoderEncoderAudioGain: 0.0
  dmrEncodeHighCutHz: 2500
  trace: false
  debug: false
  tek:
    enable: false
    tekAlgo: "aes"
    tekKeyId: 1
  localAudio: false
  voxSampleLevel: 80.0
  dropTimeMs: 600
  detectAnalogMDC1200: false
  preambleLeaderTone: false
  preambleTone: 2175
  preambleLength: 200
  udpAudio: true
  udpMetadata: true
  udpSendPort: 31120
  udpSendAddress: "127.0.0.1"
  udpReceivePort: 31122
  udpReceiveAddress: "127.0.0.1"
  udpRTPFrames: true
  udpIgnoreRTPTiming: true
  udpRTPContinuousSeq: false
  udpUseULaw: false
  udpUsrp: false
  udpFrameTiming: false
  rtsPttEnable: false
  rtsPttPort: "/dev/ttyUSB0"
  rtsPttHoldoffMs: 250
  ctsCorEnable: false
  ctsCorPort: "/dev/ttyUSB0"
  ctsCorInvert: false
  ctsCorHoldoffMs: 250
